openapi: 3.0.0
info:
  title: Video Streaming API
  version: 1.0.0

x-amazon-apigateway-cors:
  allowOrigins:
    - '*'
  allowMethods:
    - POST
  allowHeaders:
    - content-type
  maxAge: 3600

paths:
  /:
    get:
      summary: Returns an HTML page with the video player
      responses:
        200:
          description: OK
          content:
            text/html:
              schema:
                type: string
        500:
          $ref: '#/components/responses/InternalServerError'

  /dashboard:
    get:
      summary: Returns an HTML page with analytic dashboard
      responses:
        200:
          description: OK
          content:
            text/html:
              schema:
                type: string
        500:
          $ref: '#/components/responses/InternalServerError'

  /data:
    post:
      summary: Send video player data to Momento for processing
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VideoPlayerData'
      responses:
        200:
          description: OK
        500:
          $ref: '#/components/responses/InternalServerError'

components:
  schemas:
    VideoPlayerData:
      type: object
      properties:
        text:
          type: string

  responses:
    InternalServerError: #500
      description: The server encountered an unexpected condition which prevented it from fulfilling the request.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: An error occurred saving the item.
            required:
              - message
