openapi: 3.0.0
info:
  title: Video Streaming API
  version: 1.0.0

x-amazon-apigateway-cors:
  allowOrigins:
    - '*'
  allowMethods:
    - POST
  allowHeaders:
    - content-type
  maxAge: 3600

paths:
  /:
    get:
      summary: Returns an HTML page with the video player
      responses:
        200:
          description: OK
          content:
            text/html:
              schema:
                type: string
        500:
          $ref: '#/components/responses/InternalServerError'

  /dashboard:
    get:
      summary: Returns an HTML page with analytic dashboard
      responses:
        200:
          description: OK
          content:
            text/html:
              schema:
                type: string
        500:
          $ref: '#/components/responses/InternalServerError'

  /data:
    post:
      summary: Send video player data to Momento for processing
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VideoPlayerData'
      responses:
        200:
          description: OK
        500:
          $ref: '#/components/responses/InternalServerError'

  /simulations:
    post:
      summary: Start a simulation with a provided number of video players
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                playerCount:
                  type: integer
                  minimum: 1
                  maximum: 1000
              required:
                - playerCount
      responses:
        202:
          description: Accepted
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
        500:
          $ref: '#/components/responses/InternalServerError'
      x-amazon-apigateway-integration:
        payloadFormatVersion: "1.0"
        type: "http_proxy"
        httpMethod: "POST"
        uri: "https://9m27egzcnq.us-east-1.awsapprunner.com/simulations"
        connectionType: "INTERNET"
        requestTemplates:
          application/json: "$input.body"
        responses:
          default:
            statusCode: 202

components:
  schemas:
    VideoPlayerData:
      type: object
      properties:
        text:
          type: string

  responses:
    InternalServerError: #500
      description: The server encountered an unexpected condition which prevented it from fulfilling the request.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: An error occurred saving the item.
            required:
              - message
